Errors have been encountered while processing source files:

{% for source_file, exception in errors.items() %}
- {{ source_file }}:
  {% for error in exception.errors|default([exception]) %}
  - {{ error }}
  {% endfor %}

{% endfor %}

Update cancelled.
